export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const REQUEST_CENTRE_BY_PIN = 'REQUEST_CENTRE_BY_PIN'
export const REQUEST_CENTRE_BY_DIST = 'REQUEST_CENTRE_BY_DIST'
export const REQUEST_CENTRE_SUCCESS  = 'REQUEST_CENTRE_SUCCESS'
export const REQUEST_CENTRE_BY_PIN_FAILED = 'REQUEST_CENTRE_BY_PIN_FAILED'
export const REQUEST_CENTRE_BY_DIST_FAILED = 'REQUEST_CENTRE_BY_DIST_FAILED'

export const REQUEST_STATE_LIST = 'REQUEST_STATE_LIST'
export const REQUEST_STATE_LIST_SUCCESS = 'REQUEST_STATE_LIST_SUCCESS'
export const REQUEST_STATE_LIST_FAILED = 'REQUEST_STATE_LIST_FAILED'

export const REQUEST_DIST_LIST = 'REQUEST_DIST_LIST'
export const REQUEST_DIST_LIST_SUCCESS = 'REQUEST_DIST_LIST_SUCCESS'
export const REQUEST_DIST_LIST_FAILED = 'REQUEST_DIST_LIST_FAILED'